### ISSUE TITLE
Tiling/Map system replacement

### ISSUE THREAD

**Issue by ghost** [yamamushi/theasciiproject#28]
Rewrite of mapping system.

**Comment by ghost** [comment]
Any thoughts as to the approach we can take with this?

**Comment by yamamushi** [comment]
I'd like to replace the chaotic EntityMap->\* functions for directing actions with their own class for readability (and bug-fixing) sake.

As for the tiles, It's obvious from the headaches with Boost::Serialization that something is broken with the way tiles are being generated, either on the stack or as pointers. 

I'm starting to wonder if generated tiles are going out of scope for some reason...
