### ISSUE TITLE
Trying to build on Debian GNU/Linux

### ISSUE THREAD

**Issue by roobie** [yamamushi/theasciiproject#35]
Hi!

I'm trying to build the project on Debian x64 Wheexy but `ld` reports that it can't find `lSockets`. I'm wondering what lib I'm missing.

Why I'm raising it as an issue is that I cannot find it in any doc.

**Comment by Fall3nSp0rk** [comment]
You'lld need libsockets to compile methinks. Is this for the client or the server?

**Comment by yamamushi** [comment]
Which branch are you building?

**Comment by roobie** [comment]
I cloned master and I'm aiming for building both client and server.

**Comment by roobie** [comment]
I suppose it's this lib then http://www.alhem.net/Sockets?

**Comment by yamamushi** [comment]
I have the feeling you may have pulled down the old branch, try re-cloning and seeing if you're still on the master branch.

The Makefile doesn't have any references to libsockets, and that was something I used in an old experimental build. If it's still giving you problems, post your build output errors here and I'll walk through them to help you get it building.

**Comment by roobie** [comment]
All right, will do! I'll check back tomorrow.

**Comment by roobie** [comment]
Sorry everybody. Should have told you I was using the makefile-linux from the makefiles dir, which I should not have done. I was able to build it when using the makefile in the root dir. Closing.

**Comment by roobie** [comment]
Thanks for your help!

**Comment by yamamushi** [comment]
feel free to contact me - yamamushi@gmail.com , if you'd like to help continue development of this project. 

There are some pieces that I know need to be torn out and replaced so that we can continue going forward with it.
